// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.controlreturns

object ControlreturnsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.worker.statistics.StatisticsProto,
    edu.uci.ics.amber.engine.architecture.worker.workloadmetrics.WorkloadmetricsProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.CurrentInputTupleInfo,
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.ControlException,
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.TypedValue,
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.EvaluatedValue,
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.StateReturn,
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.ControlReturnV2
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkFlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9jb250cm9scmV0dXJucy5wcm90bxIsZWR1L
  nVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIaPWVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9hcmNoaXRlY
  3R1cmUvd29ya2VyL3N0YXRpc3RpY3MucHJvdG8aQmVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9hcmNoaXRlY3R1cmUvd29ya2VyL
  3dvcmtsb2FkbWV0cmljcy5wcm90bxoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIhcKFUN1cnJlbnRJbnB1dFR1cGxlSW5mbyIuChBDb
  250cm9sRXhjZXB0aW9uEhoKA21zZxgBIAEoCUII4j8FEgNtc2dSA21zZyL1AQoKVHlwZWRWYWx1ZRIvCgpleHByZXNzaW9uGAEgA
  SgJQg/iPwwSCmV4cHJlc3Npb25SCmV4cHJlc3Npb24SKgoJdmFsdWVfcmVmGAIgASgJQg3iPwoSCHZhbHVlUmVmUgh2YWx1ZVJlZ
  hIqCgl2YWx1ZV9zdHIYAyABKAlCDeI/ChIIdmFsdWVTdHJSCHZhbHVlU3RyEi0KCnZhbHVlX3R5cGUYBCABKAlCDuI/CxIJdmFsd
  WVUeXBlUgl2YWx1ZVR5cGUSLwoKZXhwYW5kYWJsZRgFIAEoCEIP4j8MEgpleHBhbmRhYmxlUgpleHBhbmRhYmxlItcBCg5FdmFsd
  WF0ZWRWYWx1ZRJaCgV2YWx1ZRgBIAEoCzI4LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLlR5c
  GVkVmFsdWVCCuI/BxIFdmFsdWVSBXZhbHVlEmkKCmF0dHJpYnV0ZXMYAiADKAsyOC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY
  XJjaGl0ZWN0dXJlLndvcmtlci5UeXBlZFZhbHVlQg/iPwwSCmF0dHJpYnV0ZXNSCmF0dHJpYnV0ZXMiLwoLU3RhdGVSZXR1cm4SI
  AoFYnl0ZXMYASABKAxCCuI/BxIFYnl0ZXNSBWJ5dGVzIrcHCg9Db250cm9sUmV0dXJuVjIShAEKEWNvbnRyb2xfZXhjZXB0aW9uG
  AEgASgLMj4uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuQ29udHJvbEV4Y2VwdGlvbkIV4j8SE
  hBjb250cm9sRXhjZXB0aW9uSABSEGNvbnRyb2xFeGNlcHRpb24ShAEKEXdvcmtlcl9zdGF0aXN0aWNzGAIgASgLMj4uZWR1LnVja
  S5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuV29ya2VyU3RhdGlzdGljc0IV4j8SEhB3b3JrZXJTdGF0aXN0a
  WNzSABSEHdvcmtlclN0YXRpc3RpY3MScAoMd29ya2VyX3N0YXRlGAMgASgOMjkuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY
  2hpdGVjdHVyZS53b3JrZXIuV29ya2VyU3RhdGVCEOI/DRILd29ya2VyU3RhdGVIAFILd29ya2VyU3RhdGUSmgEKGGN1cnJlbnRfa
  W5wdXRfdHVwbGVfaW5mbxgEIAEoCzJDLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLkN1cnJlb
  nRJbnB1dFR1cGxlSW5mb0Ia4j8XEhVjdXJyZW50SW5wdXRUdXBsZUluZm9IAFIVY3VycmVudElucHV0VHVwbGVJbmZvEnwKD2V2Y
  Wx1YXRlZF92YWx1ZRgFIAEoCzI8LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLkV2YWx1YXRlZ
  FZhbHVlQhPiPxASDmV2YWx1YXRlZFZhbHVlSABSDmV2YWx1YXRlZFZhbHVlEo0BChRzZWxmX3dvcmtsb2FkX3JldHVybhgGIAEoC
  zJALmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLlNlbGZXb3JrbG9hZFJldHVybkIX4j8UEhJzZ
  WxmV29ya2xvYWRSZXR1cm5IAFISc2VsZldvcmtsb2FkUmV0dXJuEnAKDHN0YXRlX3JldHVybhgHIAEoCzI5LmVkdS51Y2kuaWNzL
  mFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLlN0YXRlUmV0dXJuQhDiPw0SC3N0YXRlUmV0dXJuSABSC3N0YXRlUmV0d
  XJuQgcKBXZhbHVlQgniPwZIAFgAeAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.worker.statistics.StatisticsProto.javaDescriptor,
      edu.uci.ics.amber.engine.architecture.worker.workloadmetrics.WorkloadmetricsProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}