// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.controlreturns

object ControlreturnsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.worker.statistics.StatisticsProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.CurrentInputTupleInfo,
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.ControlException,
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.EvaluatedValue,
      edu.uci.ics.amber.engine.architecture.worker.controlreturns.ControlReturnV2
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkFlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9jb250cm9scmV0dXJucy5wcm90bxIsZWR1L
  nVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIaPWVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9hcmNoaXRlY
  3R1cmUvd29ya2VyL3N0YXRpc3RpY3MucHJvdG8aFXNjYWxhcGIvc2NhbGFwYi5wcm90byIXChVDdXJyZW50SW5wdXRUdXBsZUluZ
  m8iLgoQQ29udHJvbEV4Y2VwdGlvbhIaCgNtc2cYASABKAlCCOI/BRIDbXNnUgNtc2cioQEKDkV2YWx1YXRlZFZhbHVlEiAKBXZhb
  HVlGAEgASgJQgriPwcSBXZhbHVlUgV2YWx1ZRI8Cg9leHByZXNzaW9uX3R5cGUYAiABKAlCE+I/EBIOZXhwcmVzc2lvblR5cGVSD
  mV4cHJlc3Npb25UeXBlEi8KCmF0dHJpYnV0ZXMYAyADKAlCD+I/DBIKYXR0cmlidXRlc1IKYXR0cmlidXRlcyK1BQoPQ29udHJvb
  FJldHVyblYyEoQBChFjb250cm9sX2V4Y2VwdGlvbhgBIAEoCzI+LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1c
  mUud29ya2VyLkNvbnRyb2xFeGNlcHRpb25CFeI/EhIQY29udHJvbEV4Y2VwdGlvbkgAUhBjb250cm9sRXhjZXB0aW9uEoQBChF3b
  3JrZXJfc3RhdGlzdGljcxgCIAEoCzI+LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLldvcmtlc
  lN0YXRpc3RpY3NCFeI/EhIQd29ya2VyU3RhdGlzdGljc0gAUhB3b3JrZXJTdGF0aXN0aWNzEnAKDHdvcmtlcl9zdGF0ZRgDIAEoD
  jI5LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLldvcmtlclN0YXRlQhDiPw0SC3dvcmtlclN0Y
  XRlSABSC3dvcmtlclN0YXRlEpoBChhjdXJyZW50X2lucHV0X3R1cGxlX2luZm8YBCABKAsyQy5lZHUudWNpLmljcy5hbWJlci5lb
  mdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5DdXJyZW50SW5wdXRUdXBsZUluZm9CGuI/FxIVY3VycmVudElucHV0VHVwbGVJbmZvS
  ABSFWN1cnJlbnRJbnB1dFR1cGxlSW5mbxJ8Cg9ldmFsdWF0ZWRfdmFsdWUYBSABKAsyPC5lZHUudWNpLmljcy5hbWJlci5lbmdpb
  mUuYXJjaGl0ZWN0dXJlLndvcmtlci5FdmFsdWF0ZWRWYWx1ZUIT4j8QEg5ldmFsdWF0ZWRWYWx1ZUgAUg5ldmFsdWF0ZWRWYWx1Z
  UIHCgV2YWx1ZUIJ4j8GSABYAHgBYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.worker.statistics.StatisticsProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}