// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.rpc.controlcommands

@SerialVersionUID(0L)
final case class PrepareCheckpointRequest(
    checkpointId: edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity,
    estimationOnly: _root_.scala.Boolean
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[PrepareCheckpointRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = checkpointId
        if (__value.serializedSize != 0) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      
      {
        val __value = estimationOnly
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(2, __value)
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = checkpointId
        if (__v.serializedSize != 0) {
          _output__.writeTag(1, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
      {
        val __v = estimationOnly
        if (__v != false) {
          _output__.writeBool(2, __v)
        }
      };
    }
    def withCheckpointId(__v: edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity): PrepareCheckpointRequest = copy(checkpointId = __v)
    def withEstimationOnly(__v: _root_.scala.Boolean): PrepareCheckpointRequest = copy(estimationOnly = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = checkpointId
          if (__t != edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity.defaultInstance) __t else null
        }
        case 2 => {
          val __t = estimationOnly
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => checkpointId.toPMessage
        case 2 => _root_.scalapb.descriptors.PBoolean(estimationOnly)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToSingleLineUnicodeString(this)
    def companion: edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest.type = edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest
    // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest])
}

object PrepareCheckpointRequest extends scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest = {
    var __checkpointId: _root_.scala.Option[edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity] = _root_.scala.None
    var __estimationOnly: _root_.scala.Boolean = false
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __checkpointId = _root_.scala.Some(__checkpointId.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 16 =>
          __estimationOnly = _input__.readBool()
        case tag => _input__.skipField(tag)
      }
    }
    edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest(
        checkpointId = __checkpointId.getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity.defaultInstance),
        estimationOnly = __estimationOnly
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest(
        checkpointId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity]).getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity.defaultInstance),
        estimationOnly = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ControlcommandsProto.javaDescriptor.getMessageTypes().get(37)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ControlcommandsProto.scalaDescriptor.messages(37)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest(
    checkpointId = edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity.defaultInstance,
    estimationOnly = false
  )
  implicit class PrepareCheckpointRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest](_l) {
    def checkpointId: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity] = field(_.checkpointId)((c_, f_) => c_.copy(checkpointId = f_))
    def estimationOnly: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.estimationOnly)((c_, f_) => c_.copy(estimationOnly = f_))
  }
  final val CHECKPOINTID_FIELD_NUMBER = 1
  final val ESTIMATIONONLY_FIELD_NUMBER = 2
  def of(
    checkpointId: edu.uci.ics.amber.engine.common.virtualidentity.ChannelMarkerIdentity,
    estimationOnly: _root_.scala.Boolean
  ): _root_.edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest = _root_.edu.uci.ics.amber.engine.architecture.rpc.controlcommands.PrepareCheckpointRequest(
    checkpointId,
    estimationOnly
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest])
}
