apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: texera-envoy-patch
  namespace: {{ .Release.Namespace }}
spec:
  type: JSONPatch
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Release.Name }}-gateway
  jsonPatches:
    # ------------------------------------------------------------------
    # Patch Listener: WebSocket Upgrades (HTTP)
    # ------------------------------------------------------------------
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: "{{ .Release.Namespace }}/{{ .Release.Name }}-gateway/http"
      operation:
        op: "add"
        path: "/default_filter_chain/filters/0/typed_config/upgrade_configs"
        value:
          - upgrade_type: "websocket"

    # ------------------------------------------------------------------
    # Patch Listener: WebSocket Upgrades (HTTPS)
    # ------------------------------------------------------------------
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: "{{ .Release.Namespace }}/{{ .Release.Name }}-gateway/https"
      operation:
        op: "add"
        path: "/default_filter_chain/filters/0/typed_config/upgrade_configs"
        value:
          - upgrade_type: "websocket"
