apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: texera-lua-extension
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Release.Name }}-gateway
  lua:
    - type: ValueRef
      valueRef:
        name: texera-lua-script
        kind: ConfigMap
        group: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: texera-lua-script
  namespace: {{ .Release.Namespace }}
data:
  lua: |
    function envoy_on_request(request_handle)
        local uri = request_handle:headers():get(":path")
        local cuid = string.match(uri, "cuid=(%d+)")
        if cuid then
          local new_host = "computing-unit-" .. cuid .. ".{{ .Values.workflowComputingUnitPool.name }}-svc.{{ .Values.workflowComputingUnitPool.namespace }}.svc.cluster.local:{{ .Values.workflowComputingUnitPool.service.port }}"
          request_handle:headers():replace(":authority", new_host)
        end
      end
