apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  annotations:
    {{- if and .Values.gatewayConfig .Values.gatewayConfig.issuer }}
    {{- if eq (default "Issuer" .Values.gatewayConfig.issuerKind) "ClusterIssuer" }}
    cert-manager.io/cluster-issuer: {{ .Values.gatewayConfig.issuer }}
    {{- else }}
    cert-manager.io/issuer: {{ .Values.gatewayConfig.issuer }}
    {{- end }}
    {{- end }}
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      {{- if and .Values.gatewayConfig .Values.gatewayConfig.hostname }}
      hostname: {{ .Values.gatewayConfig.hostname }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      {{- if and .Values.gatewayConfig .Values.gatewayConfig.hostname }}
      hostname: {{ .Values.gatewayConfig.hostname }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ (index .Values "gatewayConfig" "tlsSecretName") | default (printf "%s-cert" .Release.Name) }}
