/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Runs as the first step of `yarn build` / `yarn build:ci`. Writes
// version.prod.ts with a timestamped build number; Angular's production
// fileReplacements (angular.json) swaps version.ts for version.prod.ts.
// Dev builds (`yarn start`) keep the static "dev" string in version.ts.
// When SOURCE_DATE_EPOCH is set the timestamp comes from it rather than the
// clock, so rebuilding the same commit reproduces the same bundle
// (https://reproducible-builds.org/specs/source-date-epoch/).

const { generate } = require("build-number-generator");
const { resolve } = require("path");
const { writeFileSync } = require("fs");

// build-number-generator only reads the local clock, so the epoch path
// reproduces its <version>.YYMMDDCCC format (CCC counts two-minute slots) in UTC.
function buildNumberFromEpoch(version, sourceDateEpoch) {
  const date = new Date(Number(sourceDateEpoch) * 1000);
  if (!/^\d+$/.test(sourceDateEpoch) || Number.isNaN(date.getTime())) {
    throw new Error(`SOURCE_DATE_EPOCH must be a whole number of seconds, got ${JSON.stringify(sourceDateEpoch)}`);
  }
  const pad = (value, width) => String(value).padStart(width, "0");
  const counter = Math.floor((date.getUTCHours() * 60 + date.getUTCMinutes()) / 2);
  const stamp =
    pad(date.getUTCFullYear() % 100, 2) + pad(date.getUTCMonth() + 1, 2) + pad(date.getUTCDate(), 2) + pad(counter, 3);
  return `${version}.${stamp}`;
}

function defaultBuildNumber(version, env = process.env) {
  const sourceDateEpoch = env.SOURCE_DATE_EPOCH;
  return sourceDateEpoch ? buildNumberFromEpoch(version, sourceDateEpoch) : generate(version);
}

// Returns the contents of version.prod.ts and version.json for a version.
function renderVersionArtifacts(version, buildNumber = defaultBuildNumber(version)) {
  const prodTs = `// AUTO-GENERATED by build-version.js — do not edit or commit.
export const Version = {
  buildNumber: ${JSON.stringify(buildNumber)},
  version: ${JSON.stringify(version)},
};
`;
  const manifestJson = JSON.stringify({ buildNumber, version }) + "\n";
  return { buildNumber, prodTs, manifestJson };
}

function main() {
  const { version } = require("./package.json");
  const { buildNumber, prodTs, manifestJson } = renderVersionArtifacts(version);
  writeFileSync(resolve(__dirname, "src", "environments", "version.prod.ts"), prodTs);
  writeFileSync(resolve(__dirname, "src", "assets", "version.json"), manifestJson);
  console.log(`build-version: ${buildNumber}`);
}

module.exports = { defaultBuildNumber, renderVersionArtifacts };

// Write files only when run directly, not when required by a test.
if (require.main === module) {
  main();
}
