header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '.dockerignore'
    - '.gitattributes'
    - 'DESCRIPTION'
    - '100.jsonl'
    - '1000.jsonl'
    - 'yarn.lock'
    - '.nvmrc'
    - '.htaccess'
    - '.gitkeep'
    - 'site.webmanifest'
    - 'line_numbers.txt'
    - 'line_numbers_crlf.txt'
    - 'numbers.txt'
    - 'random_data.csv'
    - 'a.csv'
    - 'country_sales_headerless_small.csv'
    - 'country_sales_headerless_small_multi_line.csv'
    - 'country_sales_headerless_small_multi_line_custom_delimiter.csv'
    - 'country_sales_medium.csv'
    - 'country_sales_small.csv'
    - 'country_sales_small_multi_line.csv'

  comment: on-failure
