// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.controlcommands

object ControlcommandsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.sendsemantics.partitionings.PartitioningsProto,
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.StartWorkerV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.PauseWorkerV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.ResumeWorkerV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.UpdateInputLinkingV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.AddPartitioningV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.WorkerExecutionCompletedV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.QueryStatisticsV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.QueryCurrentInputTupleV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.LocalOperatorExceptionV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.SendPythonUdfV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.RetryPythonV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.PythonPrintV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.ModifyPythonLogicV2,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.ControlCommandV2Message
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkJlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9jb250cm9sY29tbWFuZHMucHJvdG8SLGVkd
  S51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyGkdlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0Z
  WN0dXJlL3NlbmRzZW1hbnRpY3MvcGFydGl0aW9uaW5ncy5wcm90bxo1ZWR1L3VjaS9pY3MvYW1iZXIvZW5naW5lL2NvbW1vbi92a
  XJ0dWFsaWRlbnRpdHkucHJvdG8aFXNjYWxhcGIvc2NhbGFwYi5wcm90byIPCg1TdGFydFdvcmtlclYyIg8KDVBhdXNlV29ya2VyV
  jIiEAoOUmVzdW1lV29ya2VyVjIi4gEKFFVwZGF0ZUlucHV0TGlua2luZ1YyEmkKCmlkZW50aWZpZXIYASABKAsyNS5lZHUudWNpL
  mljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5QhLiPw8SCmlkZW50aWZpZXLwAQFSCmlkZW50aWZpZ
  XISXwoKaW5wdXRfbGluaxgCIAEoCzItLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5jb21tb24uTGlua0lkZW50aXR5QhHiPw4SC
  WlucHV0TGlua/ABAVIJaW5wdXRMaW5rIt4BChFBZGRQYXJ0aXRpb25pbmdWMhJMCgN0YWcYASABKAsyLS5lZHUudWNpLmljcy5hb
  WJlci5lbmdpbmUuY29tbW9uLkxpbmtJZGVudGl0eUIL4j8IEgN0YWfwAQFSA3RhZxJ7CgxwYXJ0aXRpb25pbmcYAiABKAsyQS5lZ
  HUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLnNlbmRzZW1hbnRpY3MuUGFydGl0aW9uaW5nQhTiPxESDHBhcnRpd
  GlvbmluZ/ABAVIMcGFydGl0aW9uaW5nIhwKGldvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZFYyIhMKEVF1ZXJ5U3RhdGlzdGljc1YyI
  hoKGFF1ZXJ5Q3VycmVudElucHV0VHVwbGVWMiJCChhMb2NhbE9wZXJhdG9yRXhjZXB0aW9uVjISJgoHbWVzc2FnZRgBIAEoCUIM4
  j8JEgdtZXNzYWdlUgdtZXNzYWdlIlwKD1NlbmRQeXRob25VZGZWMhIdCgRjb2RlGAEgASgJQgniPwYSBGNvZGVSBGNvZGUSKgoJa
  XNfc291cmNlGAIgASgIQg3iPwoSCGlzU291cmNlUghpc1NvdXJjZSIPCg1SZXRyeVB5dGhvblYyIjcKDVB5dGhvblByaW50VjISJ
  goHbWVzc2FnZRgBIAEoCUIM4j8JEgdtZXNzYWdlUgdtZXNzYWdlImAKE01vZGlmeVB5dGhvbkxvZ2ljVjISHQoEY29kZRgBIAEoC
  UIJ4j8GEgRjb2RlUgRjb2RlEioKCWlzX3NvdXJjZRgCIAEoCEIN4j8KEghpc1NvdXJjZVIIaXNTb3VyY2UigA4KEENvbnRyb2xDb
  21tYW5kVjIScgoMc3RhcnRfd29ya2VyGAEgASgLMjsuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZ
  XIuU3RhcnRXb3JrZXJWMkIQ4j8NEgtzdGFydFdvcmtlckgAUgtzdGFydFdvcmtlchJyCgxwYXVzZV93b3JrZXIYAiABKAsyOy5lZ
  HUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5QYXVzZVdvcmtlclYyQhDiPw0SC3BhdXNlV29ya2VyS
  ABSC3BhdXNlV29ya2VyEnYKDXJlc3VtZV93b3JrZXIYAyABKAsyPC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0d
  XJlLndvcmtlci5SZXN1bWVXb3JrZXJWMkIR4j8OEgxyZXN1bWVXb3JrZXJIAFIMcmVzdW1lV29ya2VyEoIBChBhZGRfcGFydGl0a
  W9uaW5nGAQgASgLMj8uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuQWRkUGFydGl0aW9uaW5nV
  jJCFOI/ERIPYWRkUGFydGl0aW9uaW5nSABSD2FkZFBhcnRpdGlvbmluZxKPAQoUdXBkYXRlX2lucHV0X2xpbmtpbmcYBSABKAsyQ
  i5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5VcGRhdGVJbnB1dExpbmtpbmdWMkIX4j8UEhJ1c
  GRhdGVJbnB1dExpbmtpbmdIAFISdXBkYXRlSW5wdXRMaW5raW5nEoIBChBxdWVyeV9zdGF0aXN0aWNzGAYgASgLMj8uZWR1LnVja
  S5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuUXVlcnlTdGF0aXN0aWNzVjJCFOI/ERIPcXVlcnlTdGF0aXN0a
  WNzSABSD3F1ZXJ5U3RhdGlzdGljcxKgAQoZcXVlcnlfY3VycmVudF9pbnB1dF90dXBsZRgHIAEoCzJGLmVkdS51Y2kuaWNzLmFtY
  mVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLlF1ZXJ5Q3VycmVudElucHV0VHVwbGVWMkIb4j8YEhZxdWVyeUN1cnJlbnRJb
  nB1dFR1cGxlSABSFnF1ZXJ5Q3VycmVudElucHV0VHVwbGUSnwEKGGxvY2FsX29wZXJhdG9yX2V4Y2VwdGlvbhgIIAEoCzJGLmVkd
  S51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLkxvY2FsT3BlcmF0b3JFeGNlcHRpb25WMkIb4j8YEhZsb
  2NhbE9wZXJhdG9yRXhjZXB0aW9uSABSFmxvY2FsT3BlcmF0b3JFeGNlcHRpb24SewoPc2VuZF9weXRob25fdWRmGBUgASgLMj0uZ
  WR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuU2VuZFB5dGhvblVkZlYyQhLiPw8SDXNlbmRQeXRob
  25VZGZIAFINc2VuZFB5dGhvblVkZhJyCgxweXRob25fcHJpbnQYFiABKAsyOy5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJja
  Gl0ZWN0dXJlLndvcmtlci5QeXRob25QcmludFYyQhDiPw0SC3B5dGhvblByaW50SABSC3B5dGhvblByaW50EnIKDHJldHJ5X3B5d
  GhvbhgXIAEoCzI7LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLlJldHJ5UHl0aG9uVjJCEOI/D
  RILcmV0cnlQeXRob25IAFILcmV0cnlQeXRob24SiwEKE21vZGlmeV9weXRob25fbG9naWMYGCABKAsyQS5lZHUudWNpLmljcy5hb
  WJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5Nb2RpZnlQeXRob25Mb2dpY1YyQhbiPxMSEW1vZGlmeVB5dGhvbkxvZ2ljS
  ABSEW1vZGlmeVB5dGhvbkxvZ2ljEqcBChp3b3JrZXJfZXhlY3V0aW9uX2NvbXBsZXRlZBhlIAEoCzJILmVkdS51Y2kuaWNzLmFtY
  mVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLldvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZFYyQh3iPxoSGHdvcmtlckV4ZWN1d
  GlvbkNvbXBsZXRlZEgAUhh3b3JrZXJFeGVjdXRpb25Db21wbGV0ZWRCDgoMc2VhbGVkX3ZhbHVlQgniPwZIAFgAeAFiBnByb3RvM
  w=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.sendsemantics.partitionings.PartitioningsProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}