// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.controlcommands

object ControlcommandsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.sendsemantics.partitionings.PartitioningsProto,
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.StartWorker,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.PauseWorker,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.ResumeWorker,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.UpdateInputLinking,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.AddPartitioning,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.WorkerExecutionCompleted,
      edu.uci.ics.amber.engine.architecture.worker.controlcommands.ControlCommandMessage
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkJlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9jb250cm9sY29tbWFuZHMucHJvdG8SLGVkd
  S51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyGkdlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0Z
  WN0dXJlL3NlbmRzZW1hbnRpY3MvcGFydGl0aW9uaW5ncy5wcm90bxo1ZWR1L3VjaS9pY3MvYW1iZXIvZW5naW5lL2NvbW1vbi92a
  XJ0dWFsaWRlbnRpdHkucHJvdG8aFXNjYWxhcGIvc2NhbGFwYi5wcm90byINCgtTdGFydFdvcmtlciINCgtQYXVzZVdvcmtlciIOC
  gxSZXN1bWVXb3JrZXIi4AEKElVwZGF0ZUlucHV0TGlua2luZxJpCgppZGVudGlmaWVyGAEgASgLMjUuZWR1LnVjaS5pY3MuYW1iZ
  XIuZW5naW5lLmNvbW1vbi5BY3RvclZpcnR1YWxJZGVudGl0eUIS4j8PEgppZGVudGlmaWVy8AEBUgppZGVudGlmaWVyEl8KCmluc
  HV0X2xpbmsYAiABKAsyLS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkxpbmtJZGVudGl0eUIR4j8OEglpbnB1dExpb
  mvwAQFSCWlucHV0TGluayLcAQoPQWRkUGFydGl0aW9uaW5nEkwKA3RhZxgBIAEoCzItLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZ
  S5jb21tb24uTGlua0lkZW50aXR5QgviPwgSA3RhZ/ABAVIDdGFnEnsKDHBhcnRpdGlvbmluZxgCIAEoCzJBLmVkdS51Y2kuaWNzL
  mFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuc2VuZHNlbWFudGljcy5QYXJ0aXRpb25pbmdCFOI/ERIMcGFydGl0aW9uaW5n8AEBU
  gxwYXJ0aXRpb25pbmciGgoYV29ya2VyRXhlY3V0aW9uQ29tcGxldGVkIrYGCg5Db250cm9sQ29tbWFuZBJwCgxzdGFydF93b3JrZ
  XIYASABKAsyOS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5TdGFydFdvcmtlckIQ4j8NEgtzd
  GFydFdvcmtlckgAUgtzdGFydFdvcmtlchJwCgxwYXVzZV93b3JrZXIYAiABKAsyOS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY
  XJjaGl0ZWN0dXJlLndvcmtlci5QYXVzZVdvcmtlckIQ4j8NEgtwYXVzZVdvcmtlckgAUgtwYXVzZVdvcmtlchJ0Cg1yZXN1bWVfd
  29ya2VyGAMgASgLMjouZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuUmVzdW1lV29ya2VyQhHiP
  w4SDHJlc3VtZVdvcmtlckgAUgxyZXN1bWVXb3JrZXISgQEKEWFkZF9vdXRwdXRfcG9saWN5GAQgASgLMj0uZWR1LnVjaS5pY3MuY
  W1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuQWRkUGFydGl0aW9uaW5nQhTiPxESD2FkZE91dHB1dFBvbGljeUgAUg9hZ
  GRPdXRwdXRQb2xpY3kSjQEKFHVwZGF0ZV9pbnB1dF9saW5raW5nGAUgASgLMkAuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY
  2hpdGVjdHVyZS53b3JrZXIuVXBkYXRlSW5wdXRMaW5raW5nQhfiPxQSEnVwZGF0ZUlucHV0TGlua2luZ0gAUhJ1cGRhdGVJbnB1d
  ExpbmtpbmcSpQEKGndvcmtlcl9leGVjdXRpb25fY29tcGxldGVkGGUgASgLMkYuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY
  2hpdGVjdHVyZS53b3JrZXIuV29ya2VyRXhlY3V0aW9uQ29tcGxldGVkQh3iPxoSGHdvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZEgAU
  hh3b3JrZXJFeGVjdXRpb25Db21wbGV0ZWRCDgoMc2VhbGVkX3ZhbHVlQgniPwZIAFgAeAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.sendsemantics.partitionings.PartitioningsProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}