// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.testcommands

object TestcommandsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.testcommands.StringResponse,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.IntResponse,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.Ping,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.Pong,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.Pass,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.Nested,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.MultiCall,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.ErrorCommand,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.Collect,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.GenerateNumber,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.Chain,
      edu.uci.ics.amber.engine.architecture.worker.testcommands.Recursion
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cj9lZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci90ZXN0Y29tbWFuZHMucHJvdG8SLGVkdS51Y
  2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyGjVlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3Zpc
  nR1YWxpZGVudGl0eS5wcm90bxoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIjIKDlN0cmluZ1Jlc3BvbnNlEiAKBXZhbHVlGAEgASgJQ
  griPwcSBXZhbHVlUgV2YWx1ZSIvCgtJbnRSZXNwb25zZRIgCgV2YWx1ZRgBIAEoBUIK4j8HEgV2YWx1ZVIFdmFsdWUiiAEKBFBpb
  mcSFAoBaRgBIAEoBUIG4j8DEgFpUgFpEhoKA2VuZBgCIAEoBUII4j8FEgNlbmRSA2VuZBJOCgJ0bxgDIAEoCzI1LmVkdS51Y2kua
  WNzLmFtYmVyLmVuZ2luZS5jb21tb24uQWN0b3JWaXJ0dWFsSWRlbnRpdHlCB+I/BBICdG9SAnRvIogBCgRQb25nEhQKAWkYASABK
  AVCBuI/AxIBaVIBaRIaCgNlbmQYAiABKAVCCOI/BRIDZW5kUgNlbmQSTgoCdG8YAyABKAsyNS5lZHUudWNpLmljcy5hbWJlci5lb
  mdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5QgfiPwQSAnRvUgJ0byIoCgRQYXNzEiAKBXZhbHVlGAEgASgJQgriPwcSB
  XZhbHVlUgV2YWx1ZSIeCgZOZXN0ZWQSFAoBaxgBIAEoBUIG4j8DEgFrUgFrIl4KCU11bHRpQ2FsbBJRCgNzZXEYASADKAsyNS5lZ
  HUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5QgjiPwUSA3NlcVIDc2VxIg4KDEVycm9yQ
  29tbWFuZCJoCgdDb2xsZWN0El0KB3dvcmtlcnMYASADKAsyNS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yV
  mlydHVhbElkZW50aXR5QgziPwkSB3dvcmtlcnNSB3dvcmtlcnMiEAoOR2VuZXJhdGVOdW1iZXIiYAoFQ2hhaW4SVwoFbmV4dHMYA
  SADKAsyNS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5QgriPwcSBW5leHRzUgVuZ
  Xh0cyIhCglSZWN1cnNpb24SFAoBaRgBIAEoBUIG4j8DEgFpUgFpMrcKCglSUENUZXN0ZXISdAoIU2VuZFBpbmcSMi5lZHUudWNpL
  mljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5QaW5nGjIuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpd
  GVjdHVyZS53b3JrZXIuUG9uZyIAEnQKCFNlbmRQb25nEjIuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b
  3JrZXIuUG9uZxoyLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLlBpbmciABKCAQoKU2VuZE5lc
  3RlZBI0LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLk5lc3RlZBo8LmVkdS51Y2kuaWNzLmFtY
  mVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLlN0cmluZ1Jlc3BvbnNlIgASfgoIU2VuZFBhc3MSMi5lZHUudWNpLmljcy5hb
  WJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5QYXNzGjwuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZ
  S53b3JrZXIuU3RyaW5nUmVzcG9uc2UiABKOAQoQU2VuZEVycm9yQ29tbWFuZBI6LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hc
  mNoaXRlY3R1cmUud29ya2VyLkVycm9yQ29tbWFuZBo8LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya
  2VyLlN0cmluZ1Jlc3BvbnNlIgASiAEKDVNlbmRSZWN1cnNpb24SNy5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0d
  XJlLndvcmtlci5SZWN1cnNpb24aPC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5TdHJpbmdSZ
  XNwb25zZSIAEoQBCgtTZW5kQ29sbGVjdBI1LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLkNvb
  GxlY3QaPC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5TdHJpbmdSZXNwb25zZSIAEo8BChJTZ
  W5kR2VuZXJhdGVOdW1iZXISPC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5HZW5lcmF0ZU51b
  WJlcho5LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLkludFJlc3BvbnNlIgASiAEKDVNlbmRNd
  Wx0aUNhbGwSNy5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5NdWx0aUNhbGwaPC5lZHUudWNpL
  mljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5TdHJpbmdSZXNwb25zZSIAEnkKCVNlbmRDaGFpbhIzLmVkdS51Y
  2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyLkNoYWluGjUuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvb
  W1vbi5BY3RvclZpcnR1YWxJZGVudGl0eSIAQgniPwZIAFgAeAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}