// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.statistics

object StatisticsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.statistics.WorkerStatistics,
      edu.uci.ics.amber.engine.architecture.worker.statistics.WorkerMetrics
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cj1lZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9zdGF0aXN0aWNzLnByb3RvEixlZHUudWNpL
  mljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlchoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIsYFChBXb3JrZXJTdGF0a
  XN0aWNzEpUBChFpbnB1dF90dXBsZV9jb3VudBgBIAMoCzJTLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud
  29ya2VyLldvcmtlclN0YXRpc3RpY3MuSW5wdXRUdXBsZUNvdW50RW50cnlCFOI/ERIPaW5wdXRUdXBsZUNvdW50Ug9pbnB1dFR1c
  GxlQ291bnQSmQEKEm91dHB1dF90dXBsZV9jb3VudBgCIAMoCzJULmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1c
  mUud29ya2VyLldvcmtlclN0YXRpc3RpY3MuT3V0cHV0VHVwbGVDb3VudEVudHJ5QhXiPxISEG91dHB1dFR1cGxlQ291bnRSEG91d
  HB1dFR1cGxlQ291bnQSSQoUZGF0YV9wcm9jZXNzaW5nX3RpbWUYAyABKANCF+I/FBISZGF0YVByb2Nlc3NpbmdUaW1lUhJkYXRhU
  HJvY2Vzc2luZ1RpbWUSUgoXY29udHJvbF9wcm9jZXNzaW5nX3RpbWUYBCABKANCGuI/FxIVY29udHJvbFByb2Nlc3NpbmdUaW1lU
  hVjb250cm9sUHJvY2Vzc2luZ1RpbWUSKgoJaWRsZV90aW1lGAUgASgDQg3iPwoSCGlkbGVUaW1lUghpZGxlVGltZRpYChRJbnB1d
  FR1cGxlQ291bnRFbnRyeRIaCgNrZXkYASABKAVCCOI/BRIDa2V5UgNrZXkSIAoFdmFsdWUYAiABKANCCuI/BxIFdmFsdWVSBXZhb
  HVlOgI4ARpZChVPdXRwdXRUdXBsZUNvdW50RW50cnkSGgoDa2V5GAEgASgFQgjiPwUSA2tleVIDa2V5EiAKBXZhbHVlGAIgASgDQ
  griPwcSBXZhbHVlUgV2YWx1ZToCOAEiigIKDVdvcmtlck1ldHJpY3MScQoMd29ya2VyX3N0YXRlGAEgASgOMjkuZWR1LnVjaS5pY
  3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS53b3JrZXIuV29ya2VyU3RhdGVCE+I/EBILd29ya2VyU3RhdGXwAQFSC3dvcmtlc
  lN0YXRlEoUBChF3b3JrZXJfc3RhdGlzdGljcxgCIAEoCzI+LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud
  29ya2VyLldvcmtlclN0YXRpc3RpY3NCGOI/FRIQd29ya2VyU3RhdGlzdGljc/ABAVIQd29ya2VyU3RhdGlzdGljcypTCgtXb3JrZ
  XJTdGF0ZRIRCg1VTklOSVRJQUxJWkVEEAASCQoFUkVBRFkQARILCgdSVU5OSU5HEAISCgoGUEFVU0VEEAMSDQoJQ09NUExFVEVEE
  ARCCeI/BkgAWAB4AWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}