// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.statistics

object StatisticsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.worker.statistics.WorkerStatistics
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cj1lZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3dvcmtlci9zdGF0aXN0aWNzLnByb3RvEixlZHUudWNpL
  mljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlchoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIrkGChBXb3JrZXJTdGF0a
  XN0aWNzEnEKDHdvcmtlcl9zdGF0ZRgBIAEoDjI5LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUud29ya2VyL
  ldvcmtlclN0YXRlQhPiPxASC3dvcmtlclN0YXRl8AEBUgt3b3JrZXJTdGF0ZRKVAQoRaW5wdXRfdHVwbGVfY291bnQYAiADKAsyU
  y5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5Xb3JrZXJTdGF0aXN0aWNzLklucHV0VHVwbGVDb
  3VudEVudHJ5QhTiPxESD2lucHV0VHVwbGVDb3VudFIPaW5wdXRUdXBsZUNvdW50EpkBChJvdXRwdXRfdHVwbGVfY291bnQYAyADK
  AsyVC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5Xb3JrZXJTdGF0aXN0aWNzLk91dHB1dFR1c
  GxlQ291bnRFbnRyeUIV4j8SEhBvdXRwdXRUdXBsZUNvdW50UhBvdXRwdXRUdXBsZUNvdW50EkkKFGRhdGFfcHJvY2Vzc2luZ190a
  W1lGAQgASgDQhfiPxQSEmRhdGFQcm9jZXNzaW5nVGltZVISZGF0YVByb2Nlc3NpbmdUaW1lElIKF2NvbnRyb2xfcHJvY2Vzc2luZ
  190aW1lGAUgASgDQhriPxcSFWNvbnRyb2xQcm9jZXNzaW5nVGltZVIVY29udHJvbFByb2Nlc3NpbmdUaW1lEioKCWlkbGVfdGltZ
  RgGIAEoA0IN4j8KEghpZGxlVGltZVIIaWRsZVRpbWUaWAoUSW5wdXRUdXBsZUNvdW50RW50cnkSGgoDa2V5GAEgASgFQgjiPwUSA
  2tleVIDa2V5EiAKBXZhbHVlGAIgASgDQgriPwcSBXZhbHVlUgV2YWx1ZToCOAEaWQoVT3V0cHV0VHVwbGVDb3VudEVudHJ5EhoKA
  2tleRgBIAEoBUII4j8FEgNrZXlSA2tleRIgCgV2YWx1ZRgCIAEoA0IK4j8HEgV2YWx1ZVIFdmFsdWU6AjgBKlMKC1dvcmtlclN0Y
  XRlEhEKDVVOSU5JVElBTElaRUQQABIJCgVSRUFEWRABEgsKB1JVTk5JTkcQAhIKCgZQQVVTRUQQAxINCglDT01QTEVURUQQBEIJ4
  j8GSABYAHgBYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}