// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common.workflow

@SerialVersionUID(0L)
final case class PhysicalLink(
    from: edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity = edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance,
    fromPort: edu.uci.ics.amber.engine.common.workflow.OutputPort = edu.uci.ics.amber.engine.common.workflow.OutputPort.defaultInstance,
    to: edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity = edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance,
    toPort: edu.uci.ics.amber.engine.common.workflow.InputPort = edu.uci.ics.amber.engine.common.workflow.InputPort.defaultInstance
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[PhysicalLink] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = from
        if (__value != edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      
      {
        val __value = fromPort
        if (__value != edu.uci.ics.amber.engine.common.workflow.OutputPort.defaultInstance) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      
      {
        val __value = to
        if (__value != edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      
      {
        val __value = toPort
        if (__value != edu.uci.ics.amber.engine.common.workflow.InputPort.defaultInstance) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = from
        if (__v != edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance) {
          _output__.writeTag(1, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
      {
        val __v = fromPort
        if (__v != edu.uci.ics.amber.engine.common.workflow.OutputPort.defaultInstance) {
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
      {
        val __v = to
        if (__v != edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance) {
          _output__.writeTag(3, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
      {
        val __v = toPort
        if (__v != edu.uci.ics.amber.engine.common.workflow.InputPort.defaultInstance) {
          _output__.writeTag(4, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
    }
    def withFrom(__v: edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity): PhysicalLink = copy(from = __v)
    def withFromPort(__v: edu.uci.ics.amber.engine.common.workflow.OutputPort): PhysicalLink = copy(fromPort = __v)
    def withTo(__v: edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity): PhysicalLink = copy(to = __v)
    def withToPort(__v: edu.uci.ics.amber.engine.common.workflow.InputPort): PhysicalLink = copy(toPort = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = from
          if (__t != edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance) __t else null
        }
        case 2 => {
          val __t = fromPort
          if (__t != edu.uci.ics.amber.engine.common.workflow.OutputPort.defaultInstance) __t else null
        }
        case 3 => {
          val __t = to
          if (__t != edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance) __t else null
        }
        case 4 => {
          val __t = toPort
          if (__t != edu.uci.ics.amber.engine.common.workflow.InputPort.defaultInstance) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => from.toPMessage
        case 2 => fromPort.toPMessage
        case 3 => to.toPMessage
        case 4 => toPort.toPMessage
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToSingleLineUnicodeString(this)
    def companion = edu.uci.ics.amber.engine.common.workflow.PhysicalLink
    // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.common.PhysicalLink])
}

object PhysicalLink extends scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.workflow.PhysicalLink] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.workflow.PhysicalLink] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): edu.uci.ics.amber.engine.common.workflow.PhysicalLink = {
    var __from: _root_.scala.Option[edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity] = _root_.scala.None
    var __fromPort: _root_.scala.Option[edu.uci.ics.amber.engine.common.workflow.OutputPort] = _root_.scala.None
    var __to: _root_.scala.Option[edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity] = _root_.scala.None
    var __toPort: _root_.scala.Option[edu.uci.ics.amber.engine.common.workflow.InputPort] = _root_.scala.None
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __from = _root_.scala.Some(__from.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __fromPort = _root_.scala.Some(__fromPort.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.workflow.OutputPort](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __to = _root_.scala.Some(__to.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 34 =>
          __toPort = _root_.scala.Some(__toPort.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.workflow.InputPort](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag => _input__.skipField(tag)
      }
    }
    edu.uci.ics.amber.engine.common.workflow.PhysicalLink(
        from = __from.getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance),
        fromPort = __fromPort.getOrElse(edu.uci.ics.amber.engine.common.workflow.OutputPort.defaultInstance),
        to = __to.getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance),
        toPort = __toPort.getOrElse(edu.uci.ics.amber.engine.common.workflow.InputPort.defaultInstance)
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[edu.uci.ics.amber.engine.common.workflow.PhysicalLink] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      edu.uci.ics.amber.engine.common.workflow.PhysicalLink(
        from = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity]).getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance),
        fromPort = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[edu.uci.ics.amber.engine.common.workflow.OutputPort]).getOrElse(edu.uci.ics.amber.engine.common.workflow.OutputPort.defaultInstance),
        to = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity]).getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance),
        toPort = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[edu.uci.ics.amber.engine.common.workflow.InputPort]).getOrElse(edu.uci.ics.amber.engine.common.workflow.InputPort.defaultInstance)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WorkflowProto.javaDescriptor.getMessageTypes().get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WorkflowProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity
      case 2 => __out = edu.uci.ics.amber.engine.common.workflow.OutputPort
      case 3 => __out = edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity
      case 4 => __out = edu.uci.ics.amber.engine.common.workflow.InputPort
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = edu.uci.ics.amber.engine.common.workflow.PhysicalLink(
    from = edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance,
    fromPort = edu.uci.ics.amber.engine.common.workflow.OutputPort.defaultInstance,
    to = edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity.defaultInstance,
    toPort = edu.uci.ics.amber.engine.common.workflow.InputPort.defaultInstance
  )
  implicit class PhysicalLinkLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.workflow.PhysicalLink]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, edu.uci.ics.amber.engine.common.workflow.PhysicalLink](_l) {
    def from: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity] = field(_.from)((c_, f_) => c_.copy(from = f_))
    def fromPort: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.workflow.OutputPort] = field(_.fromPort)((c_, f_) => c_.copy(fromPort = f_))
    def to: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity] = field(_.to)((c_, f_) => c_.copy(to = f_))
    def toPort: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.workflow.InputPort] = field(_.toPort)((c_, f_) => c_.copy(toPort = f_))
  }
  final val FROM_FIELD_NUMBER = 1
  final val FROMPORT_FIELD_NUMBER = 2
  final val TO_FIELD_NUMBER = 3
  final val TOPORT_FIELD_NUMBER = 4
  def of(
    from: edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity,
    fromPort: edu.uci.ics.amber.engine.common.workflow.OutputPort,
    to: edu.uci.ics.amber.engine.common.virtualidentity.PhysicalOpIdentity,
    toPort: edu.uci.ics.amber.engine.common.workflow.InputPort
  ): _root_.edu.uci.ics.amber.engine.common.workflow.PhysicalLink = _root_.edu.uci.ics.amber.engine.common.workflow.PhysicalLink(
    from,
    fromPort,
    to,
    toPort
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.PhysicalLink])
}
