/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.texera.amber.operator.source.llm

import com.fasterxml.jackson.annotation.{JsonInclude, JsonProperty, JsonPropertyDescription}
import com.kjetland.jackson.jsonSchema.annotations.JsonSchemaTitle
import com.typesafe.scalalogging.LazyLogging
import org.apache.texera.amber.core.executor.OpExecWithCode
import org.apache.texera.amber.core.storage.FileResolver
import org.apache.texera.amber.core.tuple.{Attribute, AttributeType, Schema}
import org.apache.texera.amber.core.virtualidentity.{ExecutionIdentity, WorkflowIdentity}
import org.apache.texera.amber.core.workflow.{OutputPort, PhysicalOp, SchemaPropagationFunc}
import org.apache.texera.amber.operator.metadata.{OperatorGroupConstants, OperatorInfo}
import org.apache.texera.amber.operator.source.SourceOperatorDescriptor
import org.apache.texera.amber.operator.source.scan.FolderInputResolver
import org.apache.texera.amber.util.JSONUtils.objectMapper

import scala.jdk.CollectionConverters._
import scala.util.{Failure, Success, Try}

/**
 * Source operator whose Python body is generated by an LLM at design time.
 *
 * The descriptor is a thin wrapper around the Python UDF source runtime: at compile time we
 * build OpExecWithCode(generatedCode, "python"), exactly like PythonUDFSourceOpDescV2.
 * The LLM is never called at execution time — it runs once via the /llm-source/generate
 * REST endpoint when the user clicks the "Generate" button in the property panel, and the
 * resulting code is saved with the workflow.
 *
 * Multi-table handling (MVP): the operator emits a single output stream. Each emitted row
 * carries a synthetic __table__ discriminator column identifying which logical table it
 * belongs to. The frontend offers a "Add Filter+Projection" helper that creates a
 * per-table downstream chain. Phase 2 will swap this for true multi-output ports by
 * extending the Python UDF runtime; the JSON shape here is forward-compatible.
 *
 * The generatedCode is allowed to embed the token __TEXERA_FILE_URI__ which getPhysicalOp
 * substitutes with the resolved file URI before handing the code to the worker. This keeps
 * dataset paths out of the saved workflow JSON. Phase 2 should replace the token with
 * proper OpExec param plumbing.
 */
class LLMFileSourceOpDesc extends SourceOperatorDescriptor with LazyLogging {

  @JsonProperty
  @JsonSchemaTitle("File / Folder")
  @JsonPropertyDescription("File or folder to parse. Pick from your datasets or paste a URI.")
  @JsonInclude(JsonInclude.Include.NON_ABSENT)
  var fileName: Option[String] = None

  @JsonProperty
  @JsonSchemaTitle("Hint")
  @JsonPropertyDescription(
    "Optional free-text intent for the LLM, e.g. 'extract the monthly revenue table'."
  )
  @JsonInclude(JsonInclude.Include.NON_ABSENT)
  var userHint: Option[String] = None

  @JsonProperty(defaultValue = "")
  @JsonSchemaTitle("Generated parser")
  @JsonPropertyDescription("Input your code here")
  var generatedCode: String = ""

  @JsonProperty
  @JsonSchemaTitle("Detected tables")
  @JsonPropertyDescription("Tables the LLM identified in the file (set by the Generate action).")
  var tables: java.util.List[LLMTableSpec] = new java.util.ArrayList[LLMTableSpec]()

  @JsonProperty
  @JsonSchemaTitle("Union schema")
  @JsonPropertyDescription(
    "Union of every detected table's columns plus the __table__ discriminator. Drives the operator's output schema. Set by the Generate action."
  )
  var unionColumns: java.util.List[Attribute] = new java.util.ArrayList[Attribute]()

  @JsonProperty(defaultValue = "1")
  @JsonSchemaTitle("Worker count")
  @JsonPropertyDescription("Specify how many parallel workers to launch.")
  var workers: Int = 1

  @JsonProperty
  @JsonSchemaTitle("LLM model")
  @JsonPropertyDescription("Audit: model that generated the parser.")
  @JsonInclude(JsonInclude.Include.NON_ABSENT)
  var llmModel: Option[String] = None

  @JsonProperty
  @JsonSchemaTitle("Sample hash")
  @JsonPropertyDescription("Audit: SHA-256 of the file bytes the LLM saw.")
  @JsonInclude(JsonInclude.Include.NON_ABSENT)
  var sampleHash: Option[String] = None

  @JsonProperty
  @JsonSchemaTitle("Generated at")
  @JsonPropertyDescription("Audit: ISO-8601 timestamp of generation.")
  @JsonInclude(JsonInclude.Include.NON_ABSENT)
  var generatedAt: Option[String] = None

  override def getPhysicalOp(
      workflowId: WorkflowIdentity,
      executionId: ExecutionIdentity
  ): PhysicalOp = {
    require(workers >= 1, "Need at least 1 worker.")
    require(generatedCode != null && generatedCode.trim.nonEmpty,
      "Generated code is empty. Click Generate in the property panel first.")
    val resolvedCode = withDenseUnionRows(substituteFileUri(generatedCode))
    val physicalOp = PhysicalOp
      .sourcePhysicalOp(
        workflowId,
        executionId,
        operatorIdentifier,
        OpExecWithCode(resolvedCode, "python")
      )
      .withInputPorts(operatorInfo.inputPorts)
      .withOutputPorts(operatorInfo.outputPorts)
      .withIsOneToManyOp(true)
      .withPropagateSchema(
        SchemaPropagationFunc(_ => Map(operatorInfo.outputPorts.head.id -> sourceSchema()))
      )
      .withLocationPreference(Option.empty)

    if (workers > 1) {
      physicalOp
        .withParallelizable(true)
        .withSuggestedWorkerNum(workers)
    } else {
      physicalOp.withParallelizable(false)
    }
  }

  override def operatorInfo: OperatorInfo =
    OperatorInfo(
      userFriendlyName = "LLM File Source",
      operatorDescription =
        "Reads a sample of a file (or folder of similar files) and uses an LLM to generate a Python parser tailored to it. Great for irregular shapes — PDFs with embedded tables, vendor-specific reports, oddly-structured logs.",
      operatorGroupName = OperatorGroupConstants.INPUT_GROUP,
      inputPorts = List.empty,
      outputPorts = List(OutputPort()),
      supportReconfiguration = true
    )

  override def sourceSchema(): Schema = {
    if (unionColumns != null && !unionColumns.isEmpty) {
      Schema().add(unionColumns.asScala.toList)
    } else {
      // Generate not yet run — return a placeholder schema with just the __table__
      // discriminator so downstream compile checks don't blow up before the user clicks
      // Generate. AttributeType.STRING serializes as "string" via @JsonValue, matching
      // the lowercase casing the property panel's enum dropdown expects.
      Schema().add(new Attribute("__table__", AttributeType.STRING))
    }
  }

  /**
   * Replace `__TEXERA_FILE_URI__` in the generated code with a path Python can actually open.
   *
   * The raw `fileName` property is a Texera URI (e.g., `dataset://...` or `/dataset/...`)
   * that Python libraries like pdfplumber can't resolve. We pipe the URI through
   * `FileResolver` + `DocumentFactory.asFile()` to materialize it as a local filesystem
   * file (downloading/caching the dataset blob as a side effect when needed), and embed
   * that absolute path into the generated code.
   *
   * If resolution fails (e.g., URI scheme not recognized), we fall back to the raw
   * fileName so users who manually entered a local path still get a usable substitution.
   */
  private def substituteFileUri(code: String): String = {
    val raw = fileName.getOrElse("")
    val resolved = Try {
      val uri = FileResolver.resolve(raw)
      FolderInputResolver.materializeToLocalPath(uri).toAbsolutePath.toString
    } match {
      case Success(path) =>
        logger.info(s"LLMFileSource: resolved '$raw' -> '$path'")
        path
      case Failure(err) =>
        logger.warn(s"LLMFileSource: could not resolve '$raw' (${err.getClass.getSimpleName}: ${err.getMessage}); falling back to raw fileName. The generated Python may fail to open the file.")
        raw
    }
    code.replace("__TEXERA_FILE_URI__", resolved)
  }

  /**
   * LLM-generated multi-table parsers naturally emit sparse dicts: a revenue row only contains
   * revenue fields, and a headcount row only contains headcount fields. Texera validates every
   * emitted tuple against the single union output schema, so sparse rows must be padded with nulls
   * before they reach the Python worker boundary.
   */
  private[llm] def withDenseUnionRows(code: String): String = {
    val unionColumnNames = sourceSchema().getAttributeNames
    if (unionColumnNames.isEmpty) {
      return code
    }

    val columnsLiteral = objectMapper.writeValueAsString(unionColumnNames.asJava)
    s"""$code
       |
       |# Added by LLMFileSourceOpDesc so sparse per-table rows satisfy Texera's union schema.
       |_texera_llm_source_columns = $columnsLiteral
       |_texera_llm_source_original_produce = GenerateOperator.produce
       |
       |def _texera_llm_source_dense_produce(self):
       |    for row in _texera_llm_source_original_produce(self):
       |        if isinstance(row, dict):
       |            yield {column: row.get(column) for column in _texera_llm_source_columns}
       |        else:
       |            yield row
       |
       |GenerateOperator.produce = _texera_llm_source_dense_produce
       |""".stripMargin
  }
}
