# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: edu/uci/ics/amber/engine/common/ambermessage2.proto, edu/uci/ics/amber/engine/common/statetransition2.proto, edu/uci/ics/amber/engine/common/virtualidentity.proto
# plugin: python-betterproto
import betterproto
from dataclasses import dataclass


@dataclass(eq=False, repr=False)
class ActorVirtualIdentity(betterproto.Message):
    """final case class ActorVirtualIdentity"""

    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class LayerIdentity(betterproto.Message):
    """
    final case class LayerIdentity (    workflow: String,    operator: String,
    layerID: String )
    """

    workflow: str = betterproto.string_field(1)
    operator: str = betterproto.string_field(2)
    layer_id: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class LinkIdentity(betterproto.Message):
    """
    final case class LinkIdentity (    from: LayerIdentity,    to:
    LayerIdentity )
    """

    from_: "LayerIdentity" = betterproto.message_field(1)
    to: "LayerIdentity" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class OperatorIdentity(betterproto.Message):
    """
    final case class LinkIdentity (    workflow: String,    operator: String )
    """

    workflow: str = betterproto.string_field(1)
    operator: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WorkflowIdentity(betterproto.Message):
    """final case class WorkflowIdentity (    id: String )"""

    id: str = betterproto.string_field(1)
