#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# ---------------------------------------------------------------------------
# Collect licensing artefacts from bundled jars.
#
# Walks every .jar in a given directory and extracts each jar's
# META-INF/LICENSE and META-INF/NOTICE into a staging directory.
# Also produces a concatenated NOTICE-skeleton from all extracted
# NOTICE files. Output is a starting point for human review when
# assembling or verifying LICENSE-binary.
#
# Modeled after Apache Flink's tools/releasing/collect_license_files.sh
#
# Usage:
#   ./tools/licensing/collect_binary_licenses.sh <jar-dir> [<out-dir>]
#
# Example (from sbt dist output):
#   sbt 'project WorkflowExecutionService' dist
#   unzip amber/target/universal/amber-*.zip -d /tmp/dist
#   ./tools/licensing/collect_binary_licenses.sh /tmp/dist/amber-*/lib /tmp/license-staging
# ---------------------------------------------------------------------------

set -euo pipefail

JAR_DIR="${1:?Usage: $0 <jar-dir> [<out-dir>]}"
OUT_DIR="${2:-license-staging}"

if [ ! -d "$JAR_DIR" ]; then
  echo "error: $JAR_DIR is not a directory" >&2
  exit 1
fi

TMPDIR_ROOT=$(mktemp -d)
trap 'rm -rf "$TMPDIR_ROOT"' EXIT

mkdir -p "$OUT_DIR/bundled"

total=0
has_license=0
has_notice=0

for jar in "$JAR_DIR"/*.jar; do
  [ -f "$jar" ] || continue
  total=$((total + 1))

  jar_basename=$(basename "$jar" .jar)
  tmp_extract="$TMPDIR_ROOT/$jar_basename"
  mkdir -p "$tmp_extract"

  # Extract META-INF/LICENSE* and META-INF/NOTICE* (case-insensitive)
  unzip -q -o -j "$jar" 'META-INF/LICENSE*' 'META-INF/NOTICE*' \
    -d "$tmp_extract" 2>/dev/null || true

  jar_out="$OUT_DIR/bundled/$jar_basename"
  found_anything=false

  # Copy LICENSE if extracted
  for f in "$tmp_extract"/LICENSE* "$tmp_extract"/license*; do
    if [ -f "$f" ]; then
      mkdir -p "$jar_out"
      cp "$f" "$jar_out/LICENSE"
      has_license=$((has_license + 1))
      found_anything=true
      break
    fi
  done

  # Copy NOTICE if extracted
  for f in "$tmp_extract"/NOTICE* "$tmp_extract"/notice*; do
    if [ -f "$f" ]; then
      mkdir -p "$jar_out"
      cp "$f" "$jar_out/NOTICE"
      has_notice=$((has_notice + 1))
      found_anything=true
      break
    fi
  done

  if [ "$found_anything" = false ]; then
    echo "  (no META-INF license artefacts) $jar_basename"
  fi
done

# Assemble NOTICE skeleton by concatenating all extracted NOTICE files
{
  echo "# NOTICE-skeleton"
  echo "# Generated by tools/licensing/collect_binary_licenses.sh"
  echo "# Manually curate before shipping: de-duplicate, group sensibly,"
  echo "# prepend the Apache Texera NOTICE header."
  echo ""
  for notice in "$OUT_DIR"/bundled/*/NOTICE; do
    [ -f "$notice" ] || continue
    jar_name=$(basename "$(dirname "$notice")")
    echo ""
    echo "# ---- from $jar_name ----"
    cat "$notice"
  done
} > "$OUT_DIR/NOTICE-skeleton"

echo ""
echo "Done. Scanned $total jars."
echo "  with META-INF/LICENSE: $has_license"
echo "  with META-INF/NOTICE:  $has_notice"
echo ""
echo "Output:"
echo "  per-jar extracts:  $OUT_DIR/bundled/<jar-name>/{LICENSE,NOTICE}"
echo "  NOTICE skeleton:   $OUT_DIR/NOTICE-skeleton"
