name: Release Auditing

on:
  push:
    branches:
      - 'ci-enable/**'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Check License Headers
    runs-on: ubuntu-latest
    env:
      RAT_VERSION: 0.16.1
    steps:
      - name: Setup Apache Creadur RAT
        shell: bash
        working-directory: ${{ github.action_path }}
        run: |
          set +e
          # Try Apache's Download CDN
          echo "Attempting to download from Apache's Download CDN"
          curl --fail --silent --no-progress-meter https://dlcdn.apache.org/creadur/apache-rat-${RAT_VERSION}/apache-rat-${RAT_VERSION}-bin.tar.gz --output apache-rat-${RAT_VERSION}-bin.tar.gz
  
          if [ $? -ne 0 ]; then
            # It is possible that a new version was released and last version removed from dlcdn.
            echo "Attempting to download from Apache's Archive"
            curl --no-progress-meter https://archive.apache.org/dist/creadur/apache-rat-${RAT_VERSION}/apache-rat-${RAT_VERSION}-bin.tar.gz --output apache-rat-${RAT_VERSION}-bin.tar.gz
  
            if [ $? -ne 0 ]; then
              echo "Failed to download Apache RAT"
              exit 1
            fi
          fi
          tar zxf apache-rat-${RAT_VERSION}-bin.tar.gz
