name: Release Auditing

on:
  push:
    branches:
      - 'ci-enable/**'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Check License Headers
    runs-on: ubuntu-latest
    steps:
      - uses: apache/skywalking-eyes@v0.7.0
