name: Release Auditing

on:
  push:
    branches:
      - 'ci-enable/**'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Check License Headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Apache RAT license check
        run: |
          wget https://archive.apache.org/dist/creadur/apache-rat-0.16.1/apache-rat-0.16.1-bin.zip
          unzip apache-rat-0.16.1-bin.zip
          java -jar apache-rat-0.16.1/apache-rat-0.16.1.jar -d .
